version: '3'

services:
  webserver-mysql:
    image: mysql:8.0.4
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kong3767
      - MYSQL_USER=korea
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=project
      - MYSQL_SKIP_NAME_RESOLVE=false

  webserver-java:
    image: tomcat:10.1.31-jdk21  # Tomcat 컨테이너 사용
    container_name: webserver
    ports:
      - "8080:8080"  # Tomcat 기본 포트 사용
    volumes:
      - ./target/project-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/project.war  # WAR 배포
    depends_on:
      - webserver-mysql
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - FORWARD_HEADERS_STRATEGY=native
