version: '3'
services:
  webserver-mysql:
    image: mysql:8.0.4
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kong3767
      - MYSQL_USER=korea
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=project
      - MYSQL_SKIP_NAME_RESOLVE=false

  # 웹 서버가 될 continer 정의
  webserver-java:
    container_name: webserver
    ports:
      - 80:80
#      - 443:443
    build:
      context: . # 참조할 도커파일 경로
      dockerfile: Dockerfile # 도커파일의 이름
    # 이 컨테이너는 webserver-mysql을 기반으로 동작한다는 의미
    # webserver-mysql 컨테이너 먼저 만들어라
    depends_on:
      - webserver-mysql
    restart: always
